language: csharp
mono: none
dist: xenial
dotnet: 3.1

install:
before_script:
script:
- dotnet build -c Release
- dotnet test test/BTCPayServer.Client.Tests -c Release
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd src/BTCPayServer.Client && dotnet pack /p:PackageVersion=1.0.4.$TRAVIS_BUILD_NUMBER -c Release && cd bin/Release && dotnet nuget push **/*.1.0.4.$TRAVIS_BUILD_NUMBER.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master